# Generated by Django 6.0.7 on 2026-07-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=13, unique=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
