# Generated by Django 6.0.7 on 2026-08-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=13, unique=True)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
