# Generated by Django 6.0.7 on 2026-08-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(default='', max_length=13, unique=True)),
                ('full_name', models.CharField(default='', max_length=255)),
                ('assigned_constituency_na', models.CharField(default='NA-00', max_length=20)),
                ('assigned_constituency_pa', models.CharField(default='PA-00', max_length=20)),
                ('has_voted_na', models.BooleanField(default=False)),
                ('has_voted_pa', models.BooleanField(default=False)),
                ('is_biometrically_verified', models.BooleanField(default=False)),
                ('current_session_key', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
