# Generated by Django 6.0.7 on 2026-08-04 13:29

import django.db.models.deletion
import voting_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='General Elections Pakistan', max_length=255)),
                ('election_type', models.CharField(choices=[('NATIONAL', 'National Assembly'), ('PROVINCIAL', 'Provincial Assembly')], default='NATIONAL', max_length=15)),
                ('start_time', models.DateTimeField(default=voting_app.models.get_default_start_time)),
                ('end_time', models.DateTimeField(default=voting_app.models.get_default_end_time)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency_id', models.CharField(default='NA-00', max_length=20, primary_key=True, serialize=False)),
                ('province', models.CharField(choices=[('PUNJAB', 'Punjab'), ('SINDH', 'Sindh'), ('KHYBER_PAKHTUNKHWA', 'Khyber Pakhtunkhwa'), ('BALOCHISTAN', 'Balochistan'), ('ISLAMABAD_CAPITAL', 'Islamabad Capital Territory')], default='PUNJAB', max_length=30)),
                ('assembly_type', models.CharField(choices=[('NATIONAL', 'National Assembly'), ('PROVINCIAL', 'Provincial Assembly')], default='NATIONAL', max_length=20)),
                ('registered_voters_count', models.IntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='voting_app.election')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.CharField(default='CAND-000', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('political_party', models.CharField(default='Independent', max_length=100)),
                ('assigned_symbol', models.ImageField(blank=True, null=True, upload_to='election_symbols/')),
                ('assembly_type', models.CharField(choices=[('NATIONAL', 'National Assembly'), ('PROVINCIAL', 'Provincial Assembly')], default='NATIONAL', max_length=20)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting_app.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting_app.election')),
            ],
        ),
        migrations.CreateModel(
            name='BallotBox',
            fields=[
                ('ballot_box_id', models.CharField(default='BOX-000', max_length=50, primary_key=True, serialize=False)),
                ('assembly_type', models.CharField(choices=[('NATIONAL', 'National Assembly'), ('PROVINCIAL', 'Provincial Assembly')], default='NATIONAL', max_length=20)),
                ('vote_tallies', models.JSONField(blank=True, default=dict, help_text='Stores key-value pairs of candidateId and their respective vote counts.', null=True)),
                ('total_votes_cast', models.IntegerField(blank=True, default=0, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_boxes', to='voting_app.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_boxes', to='voting_app.election')),
            ],
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('station_id', models.CharField(default='STATION-000', max_length=50, primary_key=True, serialize=False)),
                ('location_name', models.CharField(default='Government Building', max_length=255)),
                ('constituency_na', models.CharField(default='NA-0', max_length=20)),
                ('constituency_pa', models.CharField(default='PA-0', max_length=20)),
                ('is_connected_to_central_server', models.BooleanField(default=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_stations', to='voting_app.election')),
            ],
        ),
    ]
