# Generated by Django 6.0.7 on 2026-07-30 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='description',
        ),
        migrations.AddField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('NATIONAL', 'National Assembly'), ('PROVINCIAL', 'Provincial Assembly')], default='National', max_length=15),
        ),
        migrations.AddField(
            model_name='election',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2033, 2, 10, 6, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='election',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2028, 2, 10, 6, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='election',
            name='title',
            field=models.CharField(default='National', max_length=200),
        ),
    ]
